
export const USER_LIST = 'USER_LIST';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';

export const GETTING_USERNAMELIST = 'GETTING_USERNAMELIST';
export const GET_USERNAMELIST = 'GET_USERNAMELIST';
export const USER_ADDING = 'USER_ADDING';
export const USER_ADDING_SUCCESS = 'USER_ADDING_SUCCESS';
export const USER_ADDING_FAILED = 'USER_ADDING_FAILED';

export const USER_REMOVING = 'USER_REMOVING';
export const USER_REMOVE_SUCCESS = 'USER_REMOVE_SUCCESS';
export const USER_REMOVE_FAILED = 'USER_REMOVE_FAILED';

export const USER_ACTIVATING = 'USER_ACTIVATING';
export const USER_ACTIVATE_SUCCESS = 'USER_ACTIVATE_SUCCESS';
export const USER_ACTIVATE_FAILED = 'USER_ACTIVATE_FAILED';

export const USER_UPDATING = 'USER_UPDATING';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const USER_CHANGING_EMAIL = 'USER_CHANGING_EMAIL';
export const USER_CHANGED_EMAIL = 'USER_CHANGED_EMAIL';
export const USER_ERR_CHANGING_EMAIL = 'USER_ERR_CHANGING_EMAIL';

export const USER_UPDATING_AVATAR = 'USER_UPDATING_AVATAR';
export const USER_UPDATED_AVATAR = 'USER_UPDATED_AVATAR';
export const USER_ERR_UPDATING_AVATAR = 'USER_ERR_UPDATING_AVATAR';

export const USER_UPDATE_INITIAL_MOBILE = 'USER_UPDATE_INITIAL_MOBILE';
export const USER_UPDATING_MOBILENO = 'USER_UPDATING_MOBILENO';
export const USER_UPDATED_MOBILENO = 'USER_UPDATED_MOBILENO';
export const USER_ERR_UPDATING_MOBILENO = 'USER_ERR_UPDATING_MOBILENO';

export const USER_UPDATE_INITIAL_PWD = 'USER_UPDATE_INITIAL_PWD';
export const USER_UPDATING_PWD = 'USER_UPDATING_PWD';
export const USER_UPDATED_PWD = 'USER_UPDATED_PWD';
export const USER_ERR_UPDATING_PWD = 'USER_ERR_UPDATING_PWD';
